spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://127.0.0.1:5432/ai_trading_platform}
    username: ${DB_USERNAME:${USER:postgres}}
    password: ${DB_PASSWORD:}
    driver-class-name: org.postgresql.Driver
  flyway:
    enabled: true
    schemas: trading
    default-schema: trading
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
    properties:
      hibernate:
        default_schema: trading
